apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    selector:
      matchLabels:
        app: goconsumer
    template:
      metadata:
        labels:
          app: goconsumer
      spec:
        conteiners:
        - name: gointensivo
          image: diegocassandri/gointensivo:latest
          ports:
          - containerPort: 8080
